from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from ..config import load_config

console = Console()
upload_app = typer.Typer(help="Upload processed assets to Echo Frame backend")


@upload_app.command("run")
def run(
    package_dir: Path = typer.Argument(..., help="Directory generated by `echo-frame process run`"),
    dry_run: bool = typer.Option(False, help="Show upload plan without making requests"),
):
    """Placeholder upload command until backend endpoint is finalized."""

    package_dir = package_dir.expanduser().resolve()
    if not package_dir.exists():
        raise typer.BadParameter(f"Package directory not found: {package_dir}")

    config = load_config()
    table = Table(title="Upload Preview")
    table.add_column("Field")
    table.add_column("Value")
    table.add_row("Server", str(config.server_url or "<not set>"))
    table.add_row("Token", "set" if config.admin_token else "<not set>")
    table.add_row("Directory", str(package_dir))
    console.print(table)

    if dry_run:
        console.print("Dry run only. No upload performed.")
        raise typer.Exit()

    console.print(
        "Upload endpoint not yet implemented. Once backend spec is ready, this command will perform the multipart request with progress bars."
    )
