from __future__ import annotations

from pathlib import Path
import tarfile
import tempfile
from typing import Optional

import requests
import typer
from rich.console import Console
from rich.progress import Progress, TaskID
from rich.table import Table

from ..config import load_config

console = Console()
upload_app = typer.Typer(help="Upload processed assets to Echo Frame backend")


class ProgressFile:
    """File-like wrapper that tracks upload progress."""

    def __init__(self, file_path: Path, progress: Progress, task_id: TaskID):
        self.file_path = file_path
        self.file = file_path.open("rb")
        self.progress = progress
        self.task_id = task_id
        self._position = 0
        self._total_read = 0

    def read(self, size: int = -1) -> bytes:
        chunk = self.file.read(size)
        if chunk:
            self._position += len(chunk)
            self._total_read += len(chunk)
            self.progress.update(self.task_id, advance=len(chunk))
        return chunk

    def seek(self, offset: int, whence: int = 0) -> int:
        """Seek to a position in the file (needed by requests for some operations)."""
        result = self.file.seek(offset, whence)
        self._position = self.file.tell()
        return result

    def tell(self) -> int:
        """Return current file position."""
        return self.file.tell()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.file.close()


def _find_metadata(package_dir: Path) -> Optional[dict]:
    meta_path = package_dir / "metadata.json"
    if not meta_path.exists():
        return None
    try:
        import json

        return json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _build_archive(package_dir: Path) -> Path:
    package_dir = package_dir.resolve()
    tmp_dir = Path(tempfile.gettempdir())
    archive_path = tmp_dir / f"echo-frame-{package_dir.name}.tar.gz"

    with tarfile.open(archive_path, "w:gz") as tar:
        tar.add(package_dir, arcname=".")

    return archive_path


@upload_app.command("run")
def run(
    package_dir: Path = typer.Argument(..., help="Directory generated by `echo-frame process run`"),
    title: Optional[str] = typer.Option(None, help="Title for the video (defaults to directory name)"),
    duration: Optional[int] = typer.Option(
        None, "--duration-seconds", help="Video duration in seconds (overrides metadata.json)"
    ),
    dry_run: bool = typer.Option(False, help="Show upload plan without making requests"),
):
    """
    Upload a processed HLS package to the Echo Frame backend.

    Expects `metadata.json` in the package directory for duration if not provided.
    """

    package_dir = package_dir.expanduser().resolve()
    if not package_dir.exists():
        raise typer.BadParameter(f"Package directory not found: {package_dir}")

    config = load_config()
    if not config.server_url:
        console.print("[red]Server URL is not set. Run `echo-frame config init` first.[/red]")
        raise typer.Exit(code=1)
    if not config.admin_token:
        console.print("[red]Admin token is not set. Use `echo-frame config set admin_token <token>`.[/red]")
        raise typer.Exit(code=1)

    metadata = _find_metadata(package_dir)
    resolved_title = title or package_dir.name
    resolved_duration: Optional[int] = duration or (metadata or {}).get("duration_seconds")
    if resolved_duration is None:
        console.print(
            "[yellow]Duration not found in metadata.json and not provided via --duration-seconds; "
            "defaulting to 0 (consider providing an explicit value).[/yellow]"
        )
        resolved_duration = 0

    archive_path = _build_archive(package_dir)

    table = Table(title="Upload Plan")
    table.add_column("Field")
    table.add_column("Value")
    table.add_row("Server", str(config.server_url))
    table.add_row("Title", resolved_title)
    table.add_row("Duration (s)", str(resolved_duration))
    table.add_row("Package dir", str(package_dir))
    table.add_row("Archive", str(archive_path))
    console.print(table)

    if dry_run:
        console.print("[green]Dry run only. No upload performed.[/green]")
        raise typer.Exit()

    url = str(config.server_url).rstrip("/") + "/api/v1/videos/upload"

    with Progress() as progress:
        task = progress.add_task("Uploading video package...", total=archive_path.stat().st_size)

        with ProgressFile(archive_path, progress, task) as progress_file:
            files = {"package": ("package.tar.gz", progress_file, "application/gzip")}
            data = {"title": resolved_title, "duration_seconds": str(resolved_duration)}
            headers = {"Authorization": f"Bearer {config.admin_token}"}

            resp = requests.post(url, data=data, files=files, headers=headers)

    if resp.status_code != 200:
        console.print(f"[red]Upload failed [{resp.status_code}]: {resp.text}[/red]")
        raise typer.Exit(code=1)

    try:
        payload = resp.json()
    except Exception:
        console.print("[red]Upload succeeded but response was not JSON.[/red]")
        console.print(resp.text)
        raise typer.Exit(code=1)

    video_id = payload.get("video_id")
    console.print(f"[green]Upload complete.[/green] Video ID: [bold]{video_id}[/bold]")
    console.print(f"Master playlist URL (once Nginx is configured): /videos/{video_id}/master.m3u8")
